(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/crdt/statelib/examples/grow_only_set/grow_only_set_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.aneris_lang.lib Require Import list_code.
From aneris.aneris_lang.lib Require Import set_code.
From aneris.examples.crdt.statelib Require Import statelib_code.

Definition gos_init_st : val := λ: <>, set_empty #().

Definition gos_mutator : val := λ: "_i" "gs" "op", set_add "op" "gs".

Definition gos_merge : val := λ: "st1" "st2", set_union "st1" "st2".

Definition gos_crdt : val := λ: <>, (gos_init_st, gos_mutator, gos_merge).

Definition gos_init (elt_ser : val) (elt_deser : val) : val :=
  λ: "addrs" "rid",
  let: "initRes" := statelib_init (list_ser elt_ser) (list_deser elt_deser)
                    "addrs" "rid" gos_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  ("get_state", "update").
