(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/crdt/statelib/examples/grow_only_set/grow_only_set_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.aneris_lang.lib Require Import list_code.
From aneris.aneris_lang.lib Require Import set_code.
From aneris.examples.crdt.statelib Require Import statelib_code.

Definition mutator : val := λ: "_i" "gs" "op", set_add "op" "gs".

Definition set_union : val :=
  λ: "s1" "s2", set_foldl (λ: "su" "e", set_add "e" "su") "s1" "s2".

Definition set_serializer (elt_ser : serializer) := list_serializer elt_ser.

Definition merge : val := λ: "st1" "st2", set_union "st1" "st2".

Definition eval_state : val := λ: "st", "st".

Definition init_st : val := λ: <>, set_empty #().

Definition gos_crdt : val := λ: <>, (init_st, mutator, merge).

Definition st_ser (elt_ser : serializer) := set_serializer elt_ser.

Definition gos_init (elt_ser : serializer) : val :=
  λ: "addrs" "rid",
  let: "initRes" := statelib_init (st_ser elt_ser).(s_ser)
                    (st_ser elt_ser).(s_deser) "addrs" "rid" gos_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  let: "eval" := λ: "st",
  eval_state ("get_state" "st") in
  ("eval", "update").
