(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/transactional_consistency/snapshot_isolation/examples/bank_transfer/bank_transfer_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.transactional_consistency.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.transactional_consistency.snapshot_isolation.util Require Import util_code.

Definition transaction1 : val :=
  λ: "cst" "amount" "src" "dst",
  start "cst";;
  let: "vsrc" := read "cst" "src" in
  (if: "amount" ≤ "vsrc"
   then
     λ: <>,
     let: "vdst" := read "cst" "dst" in
     write "cst" "dst" ("vdst" + "amount") (write "cst" "src"
                                            ("vsrc" - "amount"))
     commitU "cst"
   else  #()).
