(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/crdt/oplib/examples/grow_only_set/grow_only_set_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib Require Import set_code.
From aneris.examples.crdt.oplib Require Import oplib_code.

Definition init_st : val := λ: <>, set_empty #().

Definition effect : val :=
  λ: "msg" "st",
  let: "v" := Fst (Fst "msg") in
  let: "_vc" := Snd (Fst "msg") in
  let: "_u" := Snd "msg" in
  set_add "v" "st".

Definition gos_crdt : val := λ: <>, (init_st, effect).

Definition gos_init val_ser val_deser : val :=
  λ: "addrs" "rid",
  let: "initRes" := oplib_init val_ser val_deser "addrs" "rid" gos_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  ("get_state", "update").
