(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/transactional_consistency/snapshot_isolation/examples/deprecated/read_your_writes/read_your_writes_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.transactional_consistency.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.transactional_consistency.snapshot_isolation.util Require Import util_code.

Definition transaction : val :=
  λ: "cst",
  start "cst";;
  write "cst" #"x" #1;;
  let: "vx" := read "cst" #"x" in
  assert: ("vx" = (SOME #1));;
  commitU "cst".

Definition transaction_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  transaction "cst".

Definition server : val := λ: "srv", init_server int_serializer "srv".
