(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/crdt/oplib/examples/table_of_counters/table_of_counters_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.aneris_lang.lib Require Import list_code.
From aneris.examples.crdt.oplib Require Import oplib_code.
From aneris.examples.crdt.oplib.examples.map_comb Require Import map_comb_code.
From aneris.examples.crdt.oplib.examples.pncounter Require Import pncounter_code.

Definition table_of_counters_effect : val :=
  λ: "msg" "st",
  map_comb_effect pncounter_init_st pncounter_effect "msg" "st".

Definition table_of_counters_init_st : val := λ: <>, map_comb_init_st #().

Definition table_of_counters_crdt : val :=
  λ: <>, (table_of_counters_init_st, table_of_counters_effect).

Definition table_of_counters_init : val :=
  λ: "addrs" "rid",
  let: "initRes" := oplib_init (prod_ser string_ser int_ser)
                    (prod_deser string_deser int_deser) "addrs" "rid"
                    table_of_counters_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  ("get_state", "update").
