(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/viewstamped_replication/vr_serialization_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib Require Import list_code.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.

(**  Serialization  *)

Definition clntId_serializer := saddr_serializer.

Definition nodeId_serializer := int_serializer.

Definition seqId_serializer := int_serializer.

Definition write_serializer val_ser :=
  prod_serializer string_serializer val_ser.

Definition read_serializer := string_serializer.

Definition rslt_serializer val_ser := option_serializer val_ser.

Definition view_serializer := int_serializer.

Definition cmt_num_serializer := int_serializer.

Definition op_num_serializer := int_serializer.

Definition request_serializer val_ser :=
  prod_serializer (prod_serializer (sum_serializer (write_serializer val_ser)
                                    read_serializer)
                   clntId_serializer)
  seqId_serializer.

Definition reply_serializer val_ser :=
  prod_serializer (prod_serializer (prod_serializer view_serializer
                                    seqId_serializer)
                   (rslt_serializer val_ser))
  clntId_serializer.

Definition log_serializer val_ser :=
  list_serializer (request_serializer val_ser).

Definition prp_serializer val_ser :=
  prod_serializer (prod_serializer (prod_serializer view_serializer
                                    (request_serializer val_ser))
                   op_num_serializer)
  cmt_num_serializer.

Definition cmt_serializer :=
  prod_serializer view_serializer cmt_num_serializer.

Definition pok_serializer :=
  prod_serializer (prod_serializer view_serializer op_num_serializer)
  nodeId_serializer.

Definition svc_serializer :=
  prod_serializer view_serializer nodeId_serializer.

Definition dvc_serializer val_ser :=
  prod_serializer (prod_serializer (prod_serializer (prod_serializer 
                                                     (prod_serializer view_serializer
                                                      (log_serializer val_ser))
                                                     view_serializer)
                                    op_num_serializer)
                   cmt_num_serializer)
  nodeId_serializer.

Definition snv_serializer val_ser :=
  prod_serializer (prod_serializer (prod_serializer view_serializer
                                    (log_serializer val_ser))
                   op_num_serializer)
  cmt_num_serializer.

Definition gst_serializer :=
  prod_serializer (prod_serializer view_serializer op_num_serializer)
  nodeId_serializer.

Definition nst_serializer val_ser :=
  prod_serializer (prod_serializer (prod_serializer (prod_serializer view_serializer
                                                     (log_serializer val_ser))
                                    op_num_serializer)
                   cmt_num_serializer)
  nodeId_serializer.

Definition msg_serializer val_ser :=
  sum_serializer (sum_serializer (sum_serializer (prp_serializer val_ser)
                                  cmt_serializer)
                  (sum_serializer pok_serializer svc_serializer))
  (sum_serializer (sum_serializer (dvc_serializer val_ser)
                   (snv_serializer val_ser))
   (sum_serializer gst_serializer (nst_serializer val_ser))).

Definition msgIn_serializer val_ser :=
  sum_serializer (msg_serializer val_ser) (request_serializer val_ser).

Definition msgOut_serializer val_ser :=
  sum_serializer (msg_serializer val_ser) (reply_serializer val_ser).

(**  Smart constructors for messages  *)

Definition prp : val :=
  λ: "v" "op" "n" "k", InjL (InjL (InjL ("v", "op", "n", "k"))).

Definition cmt : val := λ: "v" "k", InjL (InjL (InjR ("v", "k"))).

Definition pok : val := λ: "v" "n" "i", InjL (InjR (InjL ("v", "n", "i"))).

Definition svc : val := λ: "v" "i", InjL (InjR (InjR ("v", "i"))).

Definition dvc : val :=
  λ: "v" "l" "v'" "n" "k" "i",
  InjR (InjL (InjL ("v", "l", "v'", "n", "k", "i"))).

Definition snv : val :=
  λ: "v" "l" "n" "k", InjR (InjL (InjR ("v", "l", "n", "k"))).

Definition gst : val := λ: "v" "n" "i", InjR (InjR (InjL ("v", "n", "i"))).

Definition nst : val :=
  λ: "v" "l" "n" "k" "j", InjR (InjR (InjR ("v", "l", "n", "k", "j"))).

Definition req : val := λ: "op" "c" "s", ("op", "c", "s").

Definition rpl : val := λ: "v" "s" "x" "c", ("v", "s", "x", "c").
