(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/crdt/oplib/examples/pncounter/pncounter_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.aneris_lang.lib Require Import list_code.
From aneris.examples.crdt.oplib Require Import oplib_code.

Definition pncounter_effect : val :=
  λ: "msg" "counter",
  let: "delta" := Fst (Fst "msg") in
  let: "_x" := Snd (Fst "msg") in
  let: "_y" := Snd "msg" in
  "counter" + "delta".

Definition pncounter_init_st : val := λ: <>, #0.

Definition pncounter_crdt : val :=
  λ: <>, (pncounter_init_st, pncounter_effect).

Definition pncounter_init : val :=
  λ: "addrs" "rid",
  let: "initRes" := oplib_init int_ser int_deser "addrs" "rid" pncounter_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  ("get_state", "update").
