(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/reliable_communication/lib/ddb/ddb_serialization_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib Require Import map_code.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.reliable_communication Require Import client_server_code.

Definition write_serializer val_ser :=
  prod_serializer string_serializer val_ser.

Definition read_serializer := string_serializer.

Definition request_serializer val_ser :=
  sum_serializer (write_serializer val_ser) read_serializer.

Definition reply_serializer val_ser :=
  sum_serializer unit_serializer (option_serializer val_ser).
