(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/snapshot_isolation/examples/classical_example/classical_example_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.transactional_consistency.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.transactional_consistency.snapshot_isolation.util Require Import util_code.

Definition transaction1 : val :=
  λ: "cst",
  write "cst" #"x" #1;;
  write "cst" #"y" #1.

Definition transaction2 : val :=
  λ: "cst",
  write "cst" #"x" #2;;
  write "cst" #"y" #2.

Definition transaction3 : val :=
  λ: "cst",
  let: "vx" := read "cst" #"x" in
  let: "vy" := read "cst" #"y" in
  assert: ("vx" = "vy").

Definition transaction1_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  run "cst" transaction1.

Definition transaction2_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  run "cst" transaction2.

Definition transaction3_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  run "cst" transaction3.

Definition server : val := λ: "srv", init_server int_serializer "srv".
