(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/dscm/implementations/one_server/one_server_serialization_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.

(**  Serialization  *)

Definition seqId_serializer := int_serializer.

Definition write_serializer val_ser :=
  prod_serializer string_serializer val_ser.

Definition read_serializer := string_serializer.

Definition request_serializer val_ser :=
  prod_serializer (sum_serializer (write_serializer val_ser) read_serializer)
  seqId_serializer.

Definition reply_serializer val_ser :=
  prod_serializer (sum_serializer unit_serializer (option_serializer val_ser))
  seqId_serializer.
