(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/transactional_consistency/snapshot_isolation/examples/deprecated/anomalie/anomalie_code.ml *)




