(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/reliable_communication/examples/dlm_db_example/dlm_db_example_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.reliable_communication.lib.dlm Require Import dlm_code.
From aneris.examples.reliable_communication.lib.repdb Require Import repdb_code.

Definition do_writes : val :=
  λ: "lk" "wr",
  dlock_acquire "lk";;
  "wr" #"x" #37;;
  "wr" #"y" #1;;
  dlock_release "lk".

Definition dl_wait_on_read : val :=
  λ: "lk" "rd" "k" "v",
  letrec: "loop" <> :=
    dlock_acquire "lk";;
    let: "res" := "rd" "k" in
    dlock_release "lk";;
    (if: "res" = (SOME "v")
     then  #()
     else
       #() (* unsafe (fun () -> Unix.sleepf 2.0); loop ()) *);;
       "loop" #()) in
    "loop" #().

Definition do_reads : val :=
  λ: "lk" "rd",
  dl_wait_on_read "lk" "rd" #"x" #37;;
  dlock_acquire "lk";;
  let: "vy" := "rd" #"y" in
  dlock_release "lk";;
  assert: ("vy" = (SOME #1)).

Definition node0 : val :=
  λ: "clt_addr00" "clt_addr01" "dl_addr" "db_laddr",
  let: "lk_chan" := dlock_subscribe_client "clt_addr00" "dl_addr" in
  let: "db_funs" := init_client_leader_proxy int_serializer "clt_addr01"
                    "db_laddr" in
  let: "wr" := Fst "db_funs" in
  let: "_rd" := Snd "db_funs" in
  do_writes "lk_chan" "wr".

Definition node1 : val :=
  λ: "clt_addr10" "clt_addr11" "dl_addr" "db_laddr",
  let: "lk_chan" := dlock_subscribe_client "clt_addr10" "dl_addr" in
  let: "db_funs" := init_client_leader_proxy int_serializer "clt_addr11"
                    "db_laddr" in
  let: "_wr" := Fst "db_funs" in
  let: "rd" := Snd "db_funs" in
  do_reads "lk_chan" "rd".
