(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/transactional_consistency/snapshot_isolation/examples/non_repeatable_read/non_repeatable_read_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.transactional_consistency.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.transactional_consistency.snapshot_isolation.util Require Import util_code.

Definition transaction1 : val :=
  λ: "cst", start "cst";;
             write "cst" #"x" #1;;
             commitT "cst".

Definition transaction2 : val :=
  λ: "cst",
  start "cst";;
  let: "v1" := read "cst" #"x" in
  let: "v2" := read "cst" #"x" in
  assert: ("v1" = "v2");;
  commitT "cst".

Definition transaction1_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  transaction1 "cst".

Definition transaction2_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  transaction2 "cst".

Definition server : val := λ: "srv", init_server int_serializer "srv".
