(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/snapshot_isolation/examples/regular/example2/example2_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.aneris_lang.lib Require Import network_util_code.
From aneris.examples.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.snapshot_isolation.util Require Import util_code.

Definition writes_body : val :=
  λ: "cst", write "cst" #"x" #37;;
             write "cst" #"y" #1.

Definition writes_transaction : val :=
  λ: "cst", start "cst";;
             writes_body "cst";;
             commit "cst".

Definition reads_transaction : val :=
  λ: "cst",
  start "cst";;
  wait_on_key "cst" (λ: "v", "v" = #1) #"y";;
  let: "rx" := unSOME (read "cst" #"x") in
  assert: ("rx" = #37);;
  commit "cst".

Definition writes_node : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  writes_transaction "cst".

Definition node_read : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  reads_transaction "cst".

Definition server : val := λ: "srv", init_server int_serializer "srv".
