(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/snapshot_isolation/examples/regular/example1/example1_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.snapshot_isolation.util.util_deprecated Require Import util_code.

Definition example11_transaction : val :=
  λ: "cst",
  start "cst";;
  write "cst" #"x" #1;;
  let: "b" := commit "cst" in
  start "cst";;
  let: "rx" := read "cst" #"x" in
  (if: "b"
   then  assert: ("rx" = (SOME #1))
   else  assert: ("rx" = NONE));;
  commitU "cst".

Definition example11_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  example11_transaction "cst".

Definition example12_transaction : val :=
  λ: "cst",
  start "cst";;
  write "cst" #"x" #1;;
  let: "b1" := commit "cst" in
  start "cst";;
  write "cst" #"x" #2;;
  let: "b2" := commit "cst" in
  start "cst";;
  let: "rx" := read "cst" #"x" in
  (if: "b1" && "b2"
   then  assert: ("rx" = (SOME #2))
   else  #());;
  commitU "cst".

Definition example12_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  example12_transaction "cst".

Definition server : val := λ: "srv", init_server int_serializer "srv".
