(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/crdt/oplib/examples/table_of_lwwregs/table_of_lwwregs_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.aneris_lang.lib Require Import list_code.
From aneris.examples.crdt.oplib Require Import oplib_code.
From aneris.examples.crdt.oplib.examples.map_comb Require Import map_comb_code.
From aneris.examples.crdt.oplib.examples.lwwreg Require Import lwwreg_code.

Definition table_of_lwwregs_effect : val :=
  λ: "msg" "st", map_comb_effect lwwreg_init_st lwwreg_effect "msg" "st".

Definition table_of_lwwregs_init_st : val := λ: <>, map_comb_init_st #().

Definition table_of_lwwregs_crdt : val :=
  λ: <>, (table_of_lwwregs_init_st, table_of_lwwregs_effect).

Definition table_of_lwwregs_init val_ser val_deser : val :=
  λ: "addrs" "rid",
  let: "initRes" := oplib_init (prod_ser string_ser val_ser)
                    (prod_deser string_deser val_deser) "addrs" "rid"
                    table_of_lwwregs_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  ("get_state", "update").
