(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/snapshot_isolation/examples/function_call/function_call_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.snapshot_isolation.util Require Import util_code.

Definition transaction : val :=
  λ: "cst" "f",
  start "cst";;
  let: "vx" := read "cst" #"x" in
  let: "r" := "f" "vx" in
  write "cst" #"x" "r";;
  commitU "cst".

Definition client : val :=
  λ: "caddr" "kvs_addr" "f",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  transaction "cst" "f".

Definition server : val := λ: "srv", init_server int_serializer "srv".
