(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/snapshot_isolation/examples/function_call/function_call_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.snapshot_isolation Require Import snapshot_isolation_code.
From aneris.examples.snapshot_isolation.util Require Import util_code.

Definition transaction1 : val :=
  λ: "cst", start "cst";;
             write "cst" #"x" #42;;
             commitU "cst".

Definition transaction2 : val :=
  λ: "cst" "f",
  start "cst";;
  let: "r" := "f" "cst" #"x" in
  write "cst" #"y" "r";;
  commitU "cst".

Definition transaction1_client : val :=
  λ: "caddr" "kvs_addr",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  transaction1 "cst".

Definition transaction2_client : val :=
  λ: "caddr" "kvs_addr" "f",
  let: "cst" := init_client_proxy int_serializer "caddr" "kvs_addr" in
  transaction2 "cst" "f".

Definition server : val := λ: "srv", init_server int_serializer "srv".
