(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/aneris_lang/lib/coin_flip_code.ml *)

From aneris.aneris_lang Require Import ast.

Definition coin_flip : val :=
  λ: <>, let: "l" := ref #true in
          Fork (#();;
                "l" <- #false);;
          ! "l".
