(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/aneris_lang/lib/par_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib Require Import spawn_code.

Definition par : val :=
  λ: "e1" "e2",
  let: "handle" := spawn "e1" in
  let: "v2" := "e2" #() in
  let: "v1" := join "handle" in
  ("v1", "v2").

Notation "e1 ||| e2" := (par (λ: <>, e1)%E (λ: <>, e2)%E) : expr_scope.

Notation "e1 ||| e2" := (par (λ: <>, e1)%V (λ: <>, e2)%V) : val_scope.
