(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/aneris_lang/lib/set_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib Require Import list_code.

Definition set_empty : val := λ: <>, [].

Definition set_add : val :=
  λ: "x" "s", (if: list_mem "x" "s"
   then  "s"
   else  "x" :: "s").

Notation "{[ x ]}" := (set_add x (set_empty #())) (at level 1, format "{[ x ]}") : expr_scope.

Notation "{[ x ; y ; .. ; z ]}" :=
  (set_add x (set_add y .. (set_add z (set_empty #())) ..)) : expr_scope.

Definition set_mem := list_mem.

Definition set_iter := list_iter.

Definition set_foldl := list_fold.

Definition set_forall := list_forall.

Definition set_cardinal := list_length.

Definition set_subseteq : val :=
  λ: "x" "y", list_forall (λ: "e", set_mem "e" "y") "x".

Definition set_equal : val :=
  λ: "x" "y", (set_subseteq "x" "y") && (set_subseteq "y" "x").

Definition set_union : val :=
  λ: "s1" "s2", set_foldl (λ: "su" "e", set_add "e" "su") "s1" "s2".
