(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/aneris_lang/lib/spawn_code.ml *)

From aneris.aneris_lang Require Import ast.

Definition spawn : val :=
  λ: "f", let: "c" := ref NONE in
           Fork (#();;
                 "c" <- (SOME ("f" #())));;
           "c".

Definition join : val :=
  rec: "join" "c" :=
  match: ! "c" with
    NONE => "join" "c"
  | SOME "x" => "x"
  end.
