(* This file is automatically generated from the OCaml source file
<repository_root>/ml_sources/examples/crdt/oplib/examples/two_p_set/two_p_set_code.ml *)

From aneris.aneris_lang Require Import ast.
From aneris.aneris_lang.lib Require Import set_code.
From aneris.aneris_lang.lib.serialization Require Import serialization_code.
From aneris.examples.crdt.oplib Require Import oplib_code.

Definition init_st : val := λ: <>, (set_empty #(), set_empty #()).

Definition effect : val :=
  λ: "msg" "st",
  let: "v" := Fst (Fst "msg") in
  let: "_vc" := Snd (Fst "msg") in
  let: "_u" := Snd "msg" in
  match: "v" with
    InjL "w" => (set_add "w" (Fst "st"), Snd "st")
  | InjR "w" => (Fst "st", set_add "w" (Snd "st"))
  end.

Definition tps_crdt : val := λ: <>, (init_st, effect).

Definition tps_init val_ser val_deser : val :=
  λ: "addrs" "rid",
  let: "initRes" := oplib_init (sum_ser val_ser val_ser)
                    (sum_deser val_deser val_deser) "addrs" "rid" tps_crdt in
  let: "get_state" := Fst "initRes" in
  let: "update" := Snd "initRes" in
  ("get_state", "update").
